-- Добавляем поля для AI auto-responder и source tracking

-- 1. Добавляем поле is_ai_response
ALTER TABLE messages 
ADD COLUMN IF NOT EXISTS is_ai_response BOOLEAN DEFAULT false;

-- 2. Добавляем поле source (если еще не добавлено)
ALTER TABLE messages 
ADD COLUMN IF NOT EXISTS source VARCHAR(50) DEFAULT 'manual';

-- 3. Добавляем индекс для быстрого поиска AI-ответов
CREATE INDEX IF NOT EXISTS idx_messages_ai_response 
ON messages(is_ai_response) 
WHERE is_ai_response = true;

-- 4. Комментарии для документации
COMMENT ON COLUMN messages.is_ai_response IS 
'Indicates if this message was automatically generated by AI auto-responder';

COMMENT ON COLUMN messages.source IS 
'Source of the message: manual, email, zillow, airbnb, etc.';

-- 5. Обновляем существующие записи (если нужно)
UPDATE messages 
SET source = 'manual' 
WHERE source IS NULL;
