-- Добавляем поле is_ai_response в таблицу messages
-- Это позволит отличать автоматические ответы AI от ответов пользователя

ALTER TABLE messages 
ADD COLUMN IF NOT EXISTS is_ai_response BOOLEAN DEFAULT false;

-- Добавляем индекс для быстрого поиска AI-ответов
CREATE INDEX IF NOT EXISTS idx_messages_ai_response 
ON messages(is_ai_response) 
WHERE is_ai_response = true;

-- Комментарий для документации
COMMENT ON COLUMN messages.is_ai_response IS 
'Indicates if this message was automatically generated by AI auto-responder';
