-- =====================================================
-- Add Gmail Message ID to Messages Table
-- =====================================================
-- This prevents duplicate message processing
-- =====================================================

-- Add gmail_message_id to messages table
ALTER TABLE messages ADD COLUMN IF NOT EXISTS gmail_message_id TEXT;

-- Add unique constraint to prevent duplicate messages
CREATE UNIQUE INDEX IF NOT EXISTS idx_messages_gmail_message_id 
  ON messages(gmail_message_id) 
  WHERE gmail_message_id IS NOT NULL;

-- Add index for faster lookups
CREATE INDEX IF NOT EXISTS idx_messages_tenant_created 
  ON messages(tenant_id, created_at DESC);

-- Add source column if it doesn't exist
ALTER TABLE messages ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'email';

-- Add is_ai_response column if it doesn't exist
ALTER TABLE messages ADD COLUMN IF NOT EXISTS is_ai_response BOOLEAN DEFAULT false;

-- Comments
COMMENT ON COLUMN messages.gmail_message_id IS 'Gmail message ID for preventing duplicate processing';
COMMENT ON COLUMN messages.source IS 'Source of the message: email, sms, website, etc';
COMMENT ON COLUMN messages.is_ai_response IS 'Whether this message was generated by AI auto-reply';
